import React from 'react'
import Link from 'next/link'
import { ArrowLeft, PenLine, Sparkles, AlertCircle } from 'lucide-react'

export default function AiDisclaimerPage() {
    return (
        <div className="min-h-screen bg-[#fbf9f5] text-slate-800 font-sans selection:bg-[#546354]/10 pb-20">
            {/* Simple Header */}
            <header className="h-16 border-b border-slate-100 flex items-center px-6 sticky top-0 bg-[#fbf9f5]/80 backdrop-blur-md z-10">
                <div className="max-w-3xl mx-auto w-full flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-2 group">
                        <ArrowLeft className="w-4 h-4 text-slate-400 group-hover:text-[#546354] transition-colors" />
                        <span className="text-sm font-medium text-slate-500 group-hover:text-slate-800 transition-colors">Back to Storyline</span>
                    </Link>
                    <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-md bg-[#546354] flex items-center justify-center">
                            <PenLine className="w-3 h-3 text-white" />
                        </div>
                        <span className="text-sm font-serif italic text-slate-800">Storyline</span>
                    </div>
                </div>
            </header>

            <main className="max-w-3xl mx-auto px-6 pt-16">
                <div className="flex items-center gap-4 mb-6">
                    <div className="w-12 h-12 rounded-2xl bg-[#546354]/5 flex items-center justify-center">
                        <Sparkles className="w-6 h-6 text-[#546354]" />
                    </div>
                    <div>
                        <h1 className="text-4xl font-serif text-slate-800">AI Disclaimer</h1>
                        <p className="text-slate-400 text-sm uppercase tracking-widest font-bold">Important Information About AI Features</p>
                    </div>
                </div>

                <div className="prose prose-slate prose-headings:font-serif prose-headings:font-normal prose-p:text-slate-600 prose-p:leading-relaxed space-y-8 mt-12">
                    <p className="text-xl text-slate-700 leading-relaxed font-serif italic">
                        Storyline integrates advanced artificial intelligence to help you explore, structure, and refine your narratives. While these tools are powerful, they have specific limitations that every author should understand.
                    </p>

                    <section className="space-y-6">
                        <div className="flex gap-4 items-start">
                            <div className="mt-1 flex-shrink-0">
                                <AlertCircle className="w-5 h-5 text-amber-500" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-slate-800 mb-1">AI outputs may be inaccurate</h2>
                                <p>Large language models generate text based on patterns and probabilities. They can occasionally "hallucinate" or provide information that is factually incorrect, logically inconsistent, or narratively nonsensical.</p>
                            </div>
                        </div>

                        <div className="flex gap-4 items-start">
                            <div className="mt-1 flex-shrink-0">
                                <AlertCircle className="w-5 h-5 text-amber-500" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-slate-800 mb-1">You are the Editor-in-Chief</h2>
                                <p>You are solely responsible for reviewing, verifying, and editing any content generated by the AI partner. Do not rely on AI as a definitive source of historical, factual, or creative truth.</p>
                            </div>
                        </div>

                        <div className="flex gap-4 items-start">
                            <div className="mt-1 flex-shrink-0">
                                <AlertCircle className="w-5 h-5 text-[#546354]" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-slate-800 mb-1">Originality and Ownership</h2>
                                <p>AI-generated content may not always be unique and could unintentionally resemble existing works. You are responsible for ensuring the originality and appropriate use of any content you create with the assistance of AI.</p>
                            </div>
                        </div>

                        <div className="flex gap-4 items-start">
                            <div className="mt-1 flex-shrink-0">
                                <AlertCircle className="w-5 h-5 text-[#546354]" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-slate-800 mb-1">Third-Party AI Providers</h2>
                                <p>Storyline uses third-party AI services (such as Google Gemini) to generate responses. Your use of these features is also subject to the terms and policies of those providers.</p>
                            </div>
                        </div>

                        <div className="flex gap-4 items-start">
                            <div className="mt-1 flex-shrink-0">
                                <AlertCircle className="w-5 h-5 text-amber-500" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-slate-800 mb-1">Not Professional Advice</h2>
                                <p>Storyline and its AI partner do not provide professional, legal, medical, or financial advice. Any advice or feedback given regarding your storytelling process is for creative and entertainment purposes only.</p>
                            </div>
                        </div>
                    </section>

                    <section className="bg-slate-50 p-8 rounded-3xl border border-slate-100 italic text-slate-500">
                        "Artificial intelligence is a mirror, not a fountain. It can reflect your intent and help you see your work from new angles, but the creative spark must always come from you."
                    </section>

                    <section>
                        <h2 className="text-2xl text-slate-800 mb-4">Questions?</h2>
                        <p>
                            We encourage you to use AI at your own discretion as a collaborative tool. If you have any questions about how Storyline uses AI, feel free to contact us at:
                        </p>
                        <a href="mailto:mwake.dev@gmail.com" className="text-[#546354] font-medium hover:underline text-lg">
                            mwake.dev@gmail.com
                        </a>
                    </section>
                </div>

                <div className="mt-20 pt-10 border-t border-slate-100 flex justify-between items-center bg-transparent">
                    <Link href="/" className="text-xs font-bold uppercase tracking-widest text-slate-300 hover:text-[#546354] transition-colors">
                        © 2026 Storyline
                    </Link>
                    <div className="flex gap-6">
                        <Link href="/terms" className="text-xs font-bold uppercase tracking-widest text-slate-300 hover:text-[#546354] transition-colors">Terms</Link>
                        <Link href="/privacy" className="text-xs font-bold uppercase tracking-widest text-slate-300 hover:text-[#546354] transition-colors">Privacy</Link>
                    </div>
                </div>
            </main>
        </div>
    )
}
